---
title: "Working Papers"
description: Projects that have been finalized and are actively being submitted for publication.
---

## Urban Labor Supply Responses to Weather Shocks for Ugandan Uber Drivers

:::{.callout-note collapse="true"}
## Abstract

Rural-urban linkages have long been a topic of study in the developing world. Remit- tances are often a key driver of these linkages and can act as insurance against rural weather shock risk, in the absence of availability and access to formal insurance products. The emergence of new technologies, such as ride-share and mobile money platforms can be potentially transformative in allowing remittance flows to adjust more quickly to ad- verse shocks. I use a dataset of Uber driver labor supply and a rich dataset of weather indicators to estimate the effect of adverse weather shocks in rural areas on Uber drivers in Kampala, Uganda. Since I do not have explicit information on migrant status and rural connection, I leverage an external dataset of Ugandan voter registration and train a gradient boosting classifier on Ugandan surnames to predict drivers’ regions of ori- gin. I develop a switching regression estimator with exogenous switching probabilities to address the misclassification bias from the predictions. I find that a one standard deviation increase in the intensity of an agricultural shock, measured as a reduction in biomass growth, is associated with an increase of around 7 hours online in the same week, which amounts to a 20% over average hours, and then a precipitous decline in the week after. The same dynamics occur for earnings. I find that this behavior might be due to extensive margin effects driven by drivers leaving the platform for short periods. Dynamics change with whether the shock happens during the planting season of crops or not.
:::


[PDF](https://drive.google.com/file/d/1G9R6lIEuhbn38x31gmkEavoAG9AtNx0s/view?usp=sharing){.btn .btn-outline-primary .btn role="button"}

## Genetic Dilution erodes productivity: Exploring farmers’ low adoption levels of improved maize in Ethiopia

*with Cristina Chiarella, Juan Sebastian Correa and Oscar Barriga Cabanillas*

:::{.callout-note collapse="true"}
## Abstract

Despite large investments in developing new maize varieties, evidence shows that few farmers
consistently adopt this new technology over time. We use an innovative methodology that
studies the adoption trajectories of farmers over a three-round panel data set to explain low
adoption rates with heterogeneous returns to adoption. By relying on self-reported use of
improved seeds, we find a puzzling answer for why farmers do not use new seed varieties:
adoption leads to seemingly small and negative returns. Heterogeneity analysis across different
levels of comparative advantage show that farmers who adopt don’t actually have a comparative
advantage in adopting improved seed, nor do they exhibit high returns to adopting. To reconcile
this result with the expected higher yields for improved seeds, we exploit unique information
on maize DNA-fingerprinting collected over the same areas in 2018. We find that the negative
returns to adoption mask heterogeneity in the actual quality of the genetic material of the seeds
farmers categorized as improved varieties in the self-reported data. Positive returns to adoption
are found for those farmers that use higher-purity germplasm, drought-tolerant maize, and newly
released varieties. When we account for misclassification in our heterogeneity analysis, we find
that the puzzle is resolved. Our findings point to the wide dispersion of older and genetically
diluted varieties, for which poorer farmers may be paying a premium. The implications of our findings speak to the need for policies to better target context and geography, expand accessibility of improved seeds, and make higher yields varieties more inclusive.
:::

[PDF](https://drive.google.com/file/d/1sqC0W1mUMzPzQreimT22qnqsnNlIj3bc/view?usp=sharing){.btn .btn-outline-primary .btn role="button"}


## Livelihood Strategies in a Climate-change Vulnerable Region

*with Miki Doan, Heng Zhu, Anubhab Gupta and Binoy Majumder*

:::{.callout-note collapse="true"}
## Abstract

Climate change has caused a disproportionate burden on the poor in developing coun-
tries, who are primarily reliant on subsistence and small-scale agriculture for their liveli-
hood. This paper contributes to our understanding of the livelihood diversification
strategies of a vulnerable coastal population living in the Sundarbans region of India,
an archipelago in the Bay of Bengal in India and Bangladesh that has been predicted
to be on the brink of the largest exodus of the human populace. Using novel high-
frequency weekly data collected over a year on a representative sample of households,
this paper utilizes k-means clustering and unsupervised time-series clustering tech-
niques to provide new insights into how poor households adapt to climate change. Our
analysis highlights that households rely on multiple income sources and cope from week
to week through mechanisms such as local borrowing, spousal income, or changes in
expenditure. Households that rear livestock have volatile yet relatively high female
income.
:::

[PDF](https://scholar.google.com/scholar_url?url=https://ageconsearch.umn.edu/record/322365/files/24195.pdf&hl=en&sa=T&oi=gsb-gga&ct=res&cd=2&d=12962046704729585600&ei=7e1vY4C5MIqUy9YP-OmKyAQ&scisig=AAGBfm2aaJtfS_KnDh5hRc47a4cZxX41aw){.btn .btn-outline-primary .btn role="button"}


## Measuring Ethnicity and Estimating its Effects on Voting at Scale: Evidence from Uganda

*With Samuel S. Bird*

:::{.callout-note collapse="true"}
## Abstract

A large literature studies the effect of ethnicity on voting in developing countries. Yet empirically it is difficult to measure ethnicity at a scale necessary to disentangle the effect of ethnicity on voting from shared political goals that stem from living in the same location. This paper differentiates between the effects of a voter's ethnicity and their location on voting behavior. We estimate these effects by pairing voter registration data with election outcomes from polling stations throughout Uganda. We overcome the challenge of measuring ethnicity by using a machine learning algorithm that exploits variation in surnames across ethnic and linguistic groups. We use these ethnicity measures to estimate the effect of ethnicity on support for the incumbent president in the 2016 general election. We find that differences in voting by ethnicity are significant and do not vary between regions, suggesting the importance of measuring and studying ethnicity at scale.
:::

[PDF](https://drive.google.com/file/d/1Tdmr2_4DCSXIt_Q7tq1omglsgn249VgE/view?usp=sharing){.btn .btn-outline-primary .btn role="button"}

## Classification into ethnic groups in Burkina Faso using names and localities

*with Michael Kevane*

:::{.callout-note collapse="true"}
## Abstract

This paper reports on the geographic distribution of ethnic groups in Burkina Faso
using approximately six million first and last names listed in electoral registries of 2012 and 2015.
We construct, from credible ethnographic sources, an expert classification list of last names and
first names associated with geographic places (villages, communes, provinces, and regions) and
ethnic groups in Burkina Faso. Supervised machine learning used the alphabetic structure of
names as well as geographic locations to assign ethnic labels to the unclassified names. The
classification permits representation of ethnic diversity and polarisation at fine geographic scales,
and concordance of the actual ethnic distribution of people with standard ethnic maps. We find
substantial variance from the static picture conveyed by the standard ethnic maps. We use the
classification to address an important contemporary social phenomenon in Burkina Faso, Mossi
migration throughout the country. In many localities, the Mossi population is now larger than the
population of the “autochtonous” ethnic group. Using the ethnically classified names in the voter
registry data, we show that significant autochthonous ethnic discontinuities across borders appear
to be associated with significant Mossi settlement discontinuities. That is, when borders sharply
separate autochtonous ethnic groups, Mossi settlement patterns also exhibit larger discontinuities
across borders. it may be that Mossi settlements are correlated with “host” conceptualizations of
inter-ethnic accommodation. The possible endogenity of Mossi settlement patterns is a relevant
consideration in evaluating popular discourses that an inevitable consequences of Mossi settlement
will be rising inter-ethnic tension over political power and resource allocation.
:::

[PDF](https://drive.google.com/file/d/1ZCS0c89GkS4hio5WEUrMSnqJ1FYeMd0V/view?usp=sharing){.btn .btn-outline-primary .btn role="button"}

## A Group Random Coefficient Approach to Modeling Heterogeneous Returns to Technology Adoption

*With Emilia Tjernstrom, Dalia Ghanem, Oscar Barriga Cabanillas, Travis J. Lybbert, and Jeffrey D. Michler*

*Revise and Resubmit, Econometrica*

:::{.callout-note collapse="true"}
## Abstract

Our paper revisits the econometric model that Suri (2011) (S2011) used in her study of heterogeneous returns to agricultural technology adoption. We propose an alternative group random coefficient (GRC) estimation strategy and revisit the empirical puzzle of why relatively few sub-Saharan farmers adopt modern technologies. Drawing on recent developments in the nonparametric panel identification literature, we start with an unrestricted GRC model that nonparametrically identifies the returns to adoption under time homogeneity. We show that the parameters of the S2011 correlated random coefficient model (CRC) can be identified from a restricted version of the GRC method. Specifically, the model in S2011 implies a key restriction that we call linearity in comparative advantage (LCA). Our unrestricted GRC model can be used to detect identification concerns for key structural parameters from the CRC model. We illustrate our method using the same data set as the original study and find that the motivating empirical puzzle remains unsolved.
:::

[PDF](https://arefiles.ucdavis.edu/uploads/pub/2023/12/11/tgblmm.pdf){.btn .btn-outline-primary .btn role="button"}

## Evaluating a Systems Approach to Suppressive Crop Rotations in Strawberry Production

*With Rachael Goodhue, Daniel Chellemi, and Krishna Subbarao*

:::{.callout-note collapse="true"}
## Abstract

We evaluate a new, dynamic approach to suppressive crop rotations, which incorporate flexibility in cropping decisions. This “systems” approach allows a grower to change their cropping decisions mid-rotation and plant higher value crops to address cash constraints while recognizing the effect of doing so on V. dahliae populations in the soil. A grower can plant broccoli to suppress the amount of microsclerotia ($\mu s$) of disease in the soil, or plant lettuce if they need more cash in the current period. This flexibility represents a dynamic tradeoff whose intention is for suppressive crop rotations, but more broadly, it is relevant for any multi-crop production system. These production schemes must take streams of profits into account (not just profits from each crop separately), as well as any dynamic spillovers that crops may have on each other.  We use the results of a field study to calibrate a dynamic model to investigate how much this flexibility can change grower net returns, as well as how different market conditions, specifically expected prices, and levels of vertical coordination can change growers’ rotation decisions in this systems context.
:::
