# This is a basic workflow to help you get started with Actions

name: CV Compile Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert academic cv with pandoc
        uses: docker://amichuda/pandoc-latex-extra:latest
        with:
          args: >-
            --from=markdown+raw_attribute
            --to=latex
            --output=docs/cv/aleksandr_michuda_cv.pdf
            --include-in-header=docs/cv/template.tex
            docs/cv/cv.md
      - name: Convert industry resume with pandoc
        uses: docker://amichuda/pandoc-latex-extra:latest
        with:
          args: >-
            --from=markdown+raw_attribute
            --to=latex
            --output=docs/cv/aleksandr_michuda_resume.pdf
            --include-in-header=docs/cv/template.tex
            docs/cv/resume.md
      - name: setup git config
        run: |
          git config user.name "CV PDF Bot"
          git config user.email "<>"
      - name: Commit to master
        run: |
          git add docs/cv/aleksandr_michuda_cv.pdf
          git add docs/cv/aleksandr_michuda_resume.pdf
          git commit -m "Compiled CV"
          git push origin master
  dispatch_deploy:
    runs-on: ubuntu-latest
    needs: convert_via_pandoc
    steps:
      - name: Checkout website-mkdocs
        uses: actions/checkout@v2
        with:
          path : amichuda-website-mkdocs
      - name: Checkout github.io
        uses: actions/checkout@v2
        with: 
          repository: amichuda/amichuda.github.io
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          path: amichuda.github.io
      - name : check cd to each
        run: cd amichuda-website-mkdocs && pwd
      - name: check cd to other
        run: cd amichuda.github.io && pwd
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install mkdocs mkdocs-material
      - name: gh-deploy
        run: cd amichuda.github.io && mkdocs gh-deploy --config-file ../amichuda-website-mkdocs/mkdocs.yml --remote-branch master
          
