# This is a basic workflow to help you get started with Actions

name: mkdocs-deploy
on:
  repository_dispatch:
    types: [mkdocs-deploy]
  workflow_dispatch:
jobs:
  dispatch_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github.io
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Check Trigger
        run: echo ${{ github.event.client_payload.sha }}
      - name: Checkout mkdocs website
        uses: actions/checkout@v2
        with: 
          repository: amichuda/amichuda-website-mkdocs
          token: ${{ secrets.ACCESS_TOKEN }}
      - name : Check Filesystem
        run: cd .. && ls    
        
