# This is a basic workflow to help you get started with Actions

name: mkdocs-deploy
on:
  repository_dispatch:
    types: [mkdocs-deploy]
  workflow_dispatch:
jobs:
  dispatch_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github.io
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          path : amichuda.github.io
      - name: Check Trigger
        run: echo ${{ github.event.client_payload.sha }}
      - name: Checkout mkdocs website
        uses: actions/checkout@v2
        with: 
          repository: amichuda/amichuda-website-mkdocs
          token: ${{ secrets.ACCESS_TOKEN }}
          path: amichuda-website-mkdocs
      - name : check cd to each
        run: cd amichuda-website-mkdocs && pwd
      - name: check cd to other
        run: cd amichuda.github.io && pwd
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install mkdocs mkdocs-material
      - name: gh-deploy
        run: cd amichuda.github.io && mkdocs gh-deploy --config-file ../amichuda-website-mkdocs/mkdocs.yml --remote-branch master
